# Generated by Django 5.0.6 on 2024-10-20 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_content_user_is_admin_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='completed',
        ),
        migrations.AddField(
            model_name='course',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='courses_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
