# Generated by Django 5.0.6 on 2024-10-20 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0003_remove_course_completed_course_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assigned_to',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
