# Generated by Django 5.0.6 on 2024-11-02 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0008_email_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='clicked_by',
            field=models.ManyToManyField(blank=True, related_name='links_clicked', to=settings.AUTH_USER_MODEL),
        ),
    ]
