# Generated by Django 5.0.6 on 2024-11-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0010_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='has_clicked',
        ),
        migrations.DeleteModel(
            name='Click',
        ),
    ]
